version: '3'

services:
  oracle:
    image: 'sath89/oracle-12c'
    ports:
      - '8080:8080'
      - '1521:1521'
    volumes:
      - './.data:/u01/app/oracle'
    depends_on:
      - sender
    links:
      - sender
  sender:
    build: './application/metrics-within/smtp-sender'
    ports:
      - '6001:80'
